export const FETCH_STUDENTS_REQUEST = "FETCH_STUDENTS_REQUEST";
export const FETCH_STUDENTS_SUCCESS = "FETCH_STUDENTS_SUCCESS";
export const FETCH_STUDENTS_ERROR = "FETCH_STUDENTS_ERROR";
export const GET_STUDENT = "GET_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const CREATE_STUDENT = "CREATE_STUDENT";
export const EDIT_STUDENT = "EDIT_STUDENT";
export const FILTER_STUDENT = "FILTER_STUDENT";
