export const FETCH_TEACHERS_REQUEST = "FETCH_TEACHERS_REQUEST";
export const FETCH_TEACHERS_SUCCESS = "FETCH_TEACHERS_SUCCESS";
export const FETCH_TEACHERS_ERROR = "FETCH_TEACHERS_ERROR";
export const DELETE_TEACHER = "DELETE_TEACHER";
export const CREATE_TEACHER = "CREATE_TEACHER";
export const EDIT_TEACHER = 'EDIT_TEACHER';
export const FILTER_TEACHER = "FILTER_TEACHER";

